### ISSUE TITLE
[Bug 🐞]: landing gear fails to exist in game

### ISSUE THREAD

**Issue by FuryFire2004** [zer0Kerbal/Dreamer#31]
### Brief description of your issue

So basically it appears the landing gear is missing, ive tried reinstalling and everything but it never shows up in game, unless it shows up when you load this up its easy to reproduce this bug. the other parts show up just fine though...

### Steps to reproduce

Load the game, go into SPH or VAB and see if the landing gear for this thing exists which it probably wont. 

### Expected behavior

landing gear to exist

### Actual behavior

landing gear being non existant

### Environment

```shell
dev version
ksp version 1.12.3
```

### How did you download and install this?

GitHub clone (expert manual installation)

**Comment by FuryFire2004** [comment]
and yes I have fires pitter and the other dependencies

**Comment by zer0Kerbal** [comment]
I ripped out the firespitter on the local branch - there should be a firespitter patch when I upload from local.
