### ISSUE TITLE
LegalMumboJumbo

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Dreamer#4]
Legal MumboJumbo  ![gplV3](https://img.shields.io/badge/License-GPLv3-A42E2B?style=plastic&labelColor=white&logo=gnu&logoColor=A42E2B) 
- [x]  license check
- [x] LICENSE files in repo
- [x]  CKAN notification
- [x]  FORUMS:
  - [x]  adoption posting
  - [x]  adoption letter
- [x]  offline adoption documentation
- [x]  link(s) saved

**Comment by FuryFire2004** [comment]
Now we can always just avoid dirrectly infering the companies name and products but thats not very preferable

**Comment by FuryFire2004** [comment]
https://www.sncorp.com/terms-of-use/ if you wanna read it
