### ISSUE TITLE
drm-container versions

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Dreamer#44]
# add
* [ ] #63
* [ ] #64
* [ ] #65
* [ ] #66
* [ ] #68
* [ ] #69

**Comment by FuryFire2004** [comment]
if you have not done it yet snacks is easy I can do that tommarow in like a 15 min timeframe

**Comment by zer0Kerbal** [comment]
> if you have not done it yet snacks is easy I can do that tommarow in like a 15 min timeframe

Snacks would be lovely. as would USI-LS. I will create the issues.

**Comment by FuryFire2004** [comment]
Sorry forgot t do this will do later

**Comment by zer0Kerbal** [comment]
> Sorry forgot t do this will do later

all good.
