### ISSUE TITLE
[Bug 🐞]: about to start testing KAS functionality for functionality will post updates on that here. edit: kas functionality is broken, same goes for the tail fin which now attaches at an offset node

### ISSUE THREAD

**Issue by FuryFire2004** [zer0Kerbal/Dreamer#47]
### Brief description of your issue

tail fin's attach node is offset to the right making the part not okay
also kas compatability is broken

### Steps to reproduce

dowload and use the mod

### Expected behavior

a node that is right under the fin

### Actual behavior

^

### Environment

its rainy where i am rn

### How did you download and install this?

GitHub clone (expert manual installation)

**Comment by FuryFire2004** [comment]
and if it needs tweaking

**Comment by FuryFire2004** [comment]
for refference incase something goes terribly wrong my very short modlist 
![image](https://user-images.githubusercontent.com/30536275/159049454-f093e3e2-c178-453f-a9d2-6ee97e6533c8.png)

**Comment by FuryFire2004** [comment]
suprissingly the only broken things in this pack is scatter but thats because i need to update it

**Comment by FuryFire2004** [comment]
btw  while im at it im gonna test stuff like glide proformance and all that so we get a good idea of stuff and things

**Comment by FuryFire2004** [comment]
node is offset which breaks this part FYI 
![image](https://user-images.githubusercontent.com/30536275/159053171-3b6950bc-eab4-4be5-979b-331535b179a8.png)

**Comment by FuryFire2004** [comment]
issues with kas
it has no storge and is a non functional part

**Comment by FuryFire2004** [comment]
poor cargo bay inset

**Comment by FuryFire2004** [comment]
mfw 
![image](https://user-images.githubusercontent.com/30536275/159054385-53c473de-4153-40bc-af65-f52177164740.png)

**Comment by FuryFire2004** [comment]
anyways along with that the duplicated parts are the other bit but really it seams to otherwise be shaping up...

**Comment by FuryFire2004** [comment]
im gonna add a hullcam config for the reer port along with docking alignment config

**Comment by FuryFire2004** [comment]
i made a push request on the hullcam patch its a clean push unlike my others, because i finally learned not to push my entire fork at once lel

**Comment by FuryFire2004** [comment]
> mfw ![image](https://user-images.githubusercontent.com/30536275/159054385-53c473de-4153-40bc-af65-f52177164740.png)

this part its... its.... its.. Beautiful!

**Comment by zer0Kerbal** [comment]
certain parts should only show up if related MOD is installed (like KIS,KAS,TAC-LS)
I know that part - but just don't remember what it is for - unless it is a service module...

Once I have the Localization branch merged in - (hopefully today) then much easier to proceed since it will be a clean, uniform base.

If I remember correctly - it flies better than the real shuttle did. ;p

**Comment by FuryFire2004** [comment]
> certain parts should only show up if related MOD is installed (like KIS,KAS,TAC-LS) I know that part - but just don't remember what it is for - unless it is a service module...
> 
> Once I have the Localization branch merged in - (hopefully today) then much easier to proceed since it will be a clean, uniform base.
> 
> If I remember correctly - it flies better than the real shuttle did. ;p

ok so basic KAS adds inventory storage space a kas winch and kas attacment point all in one part for the cargo bay, its for rescue missions and servicing missions and such... this part has none of these functions now

**Comment by FuryFire2004** [comment]
![image](https://user-images.githubusercontent.com/30536275/159133792-fec4532e-3395-48dd-adc5-ab6055db6594.png)

**Comment by zer0Kerbal** [comment]
IIRC KSP 1.8 borked KAS - pita. Thankfully @IgorZ is working on a new version of both KIS/KAS that works in 1.12.3
the part I was referring to was:
https://user-images.githubusercontent.com/30536275/159054385-53c473de-4153-40bc-af65-f52177164740.png

**Comment by FuryFire2004** [comment]
> IIRC KSP 1.8 borked KAS - pita. Thankfully @igorz is working on a new version of both KIS/KAS that works in 1.12.3 the part I was referring to was: https://user-images.githubusercontent.com/30536275/159054385-53c473de-4153-40bc-af65-f52177164740.png

im using kas and kis and both still work on 1.12.3

**Comment by FuryFire2004** [comment]
> certain parts should only show up if related MOD is installed (like KIS,KAS,TAC-LS)
> 
> I know that part - but just don't remember what it is for - unless it is a service module...
> 
> 
> 
> Once I have the Localization branch merged in - (hopefully today) then much easier to proceed since it will be a clean, uniform base.
> 
> 
> 
> If I remember correctly - it flies better than the real shuttle did. ;p

god I hope it flies better...  if not I might just have to deal with the drag cubes
