### ISSUE TITLE
can you add a extra's folder so i can do a oms cryoengine optional patch? [Documentation Issue 📚]: 

### ISSUE THREAD

**Issue by FuryFire2004** [zer0Kerbal/Dreamer#54]
### Which document/file?

It would be nice

### Brief description of your issue

nice

**Comment by FuryFire2004** [comment]
nvm

**Comment by zer0Kerbal** [comment]
FYI: (in case you needed it)

`GameData/Dreamer/Compatibility/Cryoengine/...`

`:NEEDS[CryoEngines]`
