### ISSUE TITLE
[Request]: patch for MechJeb (MJ)

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Dreamer#58]
### Description of the new feature / enhancement

add a compatibility patch for patch for MechJeb (MJ)

### Proposed technical implementation details

1. create the patch [MechJeb.cfg]

**Comment by zer0Kerbal** [comment]
@FuryFire2004

**Comment by FuryFire2004** [comment]
huh

**Comment by FuryFire2004** [comment]
did it not work cuz i have things i might need to add to it i was unsure

**Comment by FuryFire2004** [comment]
depends if it worked

**Comment by FuryFire2004** [comment]
nvm then

**Comment by FuryFire2004** [comment]
i checked another mod's mecghjeb patch, it should work given mine functions the same pretty much

**Comment by zer0Kerbal** [comment]
> i checked another mod's mecghjeb patch, it should work given mine functions the same pretty much

just the workflow. :D merged in so all is good, until it isn't. :)
