### ISSUE TITLE
[drm-container] for Snacks

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Dreamer#63]

**Comment by AtomikkuSan** [comment]
I'll see what I can do :)
What files would I need to edit?

**Comment by FuryFire2004** [comment]
I was gonna do this but sure

**Comment by FuryFire2004** [comment]
basicly the life support cargo pallet and cabins need snacks the life support thing should have a enough snacks for lets say like a 30 day trip and the cabin should have like 7 days of snacks

**Comment by FuryFire2004** [comment]
@AtomikkuSan i playtested the adoption brach and its not at all playable

**Comment by FuryFire2004** [comment]
iva completly broken, tail does not attach proporly. same with the entire centar rocket

**Comment by FuryFire2004** [comment]
not to mention that my patch for hullcam aparently just does not work

**Comment by zer0Kerbal** [comment]
> iva completly broken, tail does not attach proporly. same with the entire centar rocket


> not to mention that my patch for hullcam aparently just does not work and i dont even know why

This is no way close to being playable. Maybe After Phase IS (1.5) and Phase II -

**Comment by FuryFire2004** [comment]
yep noted. I originally was under the impression that this was in a better state than it is right now, ethier way I'm gonna fix my hullcam patch for the third time tommarow;)

**Comment by zer0Kerbal** [comment]
> yep noted. I originally was under the impression that this was in a better state than it is right now, ethier way I'm gonna fix my hullcam patch for the third time tommarow;)

let me get Phase-IS done and merged back into dev branch - I will put the :NEEDS :FOR back on then.

**Comment by FuryFire2004** [comment]
Ok well ig I'm gonna sleep cuz it's like 2 am
