### ISSUE TITLE
Clean out duplicate textures/models

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Dreamer#71]
Clean out duplicate textures/models

**Comment by FuryFire2004** [comment]
Not sure how it got to be like this but the duplicate parts cant be understood by me unless im aware of exactly what you did when you first adopted this. its from what i can tell  a mash up of the origional files and some kind of automated thing changing them when you forked/ cloned this.

**Comment by zer0Kerbal** [comment]
> Not sure how it got to be like this but the duplicate parts cant be understood by me unless I'm aware of exactly what you did when you first adopted this. its from what i can tell a mash up of the original files and some kind of automated thing changing them when you forked/ cloned this. to add on to this, no matter what we do removing the duplicates is gonna cause patches and cfgs to break (especially mine) as they likely reference the wrong things. which makes me think the best way to deal with this is Russian rouletting the duplicates and then fixing the things it breaks:(

which is why the repo wasn't ready - until I get done with my initial work - things like this unfortunately happen.

when I get done with the phaseIS (1.5) and phaseII then it will be ready for further input. 99.99% of the core will be ready - including any file name changes, part title changes, etc.

**Comment by FuryFire2004** [comment]
Ok that’s fine I will help hash out the issues ig once you have that stuff
sorted out, take your time lel.
