### ISSUE TITLE
[Bug 🐞]: IVA BROKEN

### ISSUE THREAD

**Issue by FuryFire2004** [zer0Kerbal/Dreamer#72]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/30536275/159358126-72f21202-86da-4f1a-958f-607c15e4d867.png)
this should have 7 people and be inside the craft and MAS compatability seams broken!

### Steps to reproduce

do it

### Expected behavior

work

### Actual behavior

not work

### Environment

```shell
dev branch
ksp 1.12.3
```

### How did you download and install this?

GitHub clone (expert manual installation)

**Comment by FuryFire2004** [comment]
cabin light also does not work

**Comment by zer0Kerbal** [comment]
I haven't even looked at the IVA - no reason to until it is time.

**Comment by FuryFire2004** [comment]
oh ok well I can perhaps give a few ideas and code tid bits relating to it once you get to it :)

**Comment by FuryFire2004** [comment]
I have this layout in mind involving a really cozy layout in the back of the ship which we could probably do with near future props if we really want to.

**Comment by zer0Kerbal** [comment]
the IVA is fine for this release. Already too many moving parts.

**Comment by FuryFire2004** [comment]
Yup but this is gonna be something I will work on in my branch mainly
