### ISSUE TITLE
[Bug 🐞]: undocking rear port undocks the port from dreamer

### ISSUE THREAD

**Issue by FuryFire2004** [zer0Kerbal/Dreamer#73]
### Brief description of your issue

no

### Steps to reproduce

undocking rear port

### Expected behavior

working

### Actual behavior

broken

### Environment

```shell
dev
1.12.3
cloned
```

### How did you download and install this?

GitHub clone (expert manual installation)

**Comment by zer0Kerbal** [comment]
might be similar to https://github.com/zer0Kerbal/Pteron/issues/13
from the release notes:
> [ModuleDockingNode]: referenceAttachNode = bottom instead of top - this made it REALLY hard to dock!

**Comment by FuryFire2004** [comment]
it's really hard to tell which end of the port is the right end as well tho
