### ISSUE TITLE
[Bug 🐞]: centar attach node is broken,

### ISSUE THREAD

**Issue by FuryFire2004** [zer0Kerbal/Dreamer#74]
### Brief description of your issue

it literally does not attach

### Steps to reproduce

e

### Expected behavior

e

### Actual behavior

e

### Environment

```shell
dev
1.12.3
```

### How did you download and install this?

GitHub clone (expert manual installation)

**Comment by zer0Kerbal** [comment]
@FuryFire2004 need to introduce you to my little friend: NodeHelper.

**Comment by FuryFire2004** [comment]
this is gonna have to wait until tommarow when I get home but I will send more detailed things then...

**Comment by FuryFire2004** [comment]
Btw @zer0Kerbal I flight tested what we have and the body lift is def gonna need to go down from 5 cuz a tap of the w key pulls 15 Gs and it literally is getting more lift than most of my normal planes lel. I suggest setting it at like 1.5-2
