### ISSUE TITLE
Needs a wiki

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Dreamer#8]
From WhimChaser created by [zer0Kerbal](https://github.com/zer0Kerbal): zer0Kerbal/WhimChaser#4  

needs a wiki

- [ ] create wiki

**Comment by FuryFire2004** [comment]
I can probs do this lel

**Comment by zer0Kerbal** [comment]
maybe look at https://github.com/zer0Kerbal/Komplexity/wiki and https://zer0kerbal.github.io/Taerobee/ for inspiration.

**Comment by FuryFire2004** [comment]
yea I can do something like that though not as grand given the size of the mod.

**Comment by FuryFire2004** [comment]
I'm thinking that I can include a build guide similar to this https://github.com/Rodg88/BumbleBee/wiki/Build-Guide

**Comment by FuryFire2004** [comment]
ive started on it fyi but its very WIP

**Comment by FuryFire2004** [comment]
Ok so if you go on the wiki tab for this mod ive started stuff, its not gonna really say much until the mod gets more complete so i can play through stuff like a launch profile (although ive estimated one its not very good for talking about the glide profile given i cant estimate that)
